Issue 264 test gen mock command
Spyro-Soft/scargo pull request #326
Opened 2023-08-22 07:13 UTC by MichalMendrala

2023-08-24 05:10 UTC, KonradTajstra requested changes
As far as I can see this PR focuses on testing certificates generation, however issue 264 is about generating mocks for unit tests (in gmock) - please change the title

2023-08-28 10:58 UTC, KonradTajstra submitted a review, later dismissed
Please squash commits when merging

2023-08-28 11:13 UTC, BartBart-pl approved these changes

2023-08-28 11:13 UTC, BartBart-pl commented on tests/ut/ut_scargo_gen.py
> +        {"proj_path": "coppy_test_project_stm32", "src_files_dir": "src"},
coppy

2023-08-28 11:13 UTC, BartBart-pl commented on tests/ut/ut_scargo_gen.py
> +        assert os.path.exists(f"{CERTS_DIR}/private/iot-device.key.pem")
Maybe assume instead of assert to check all conditions?

2023-09-11 09:56 UTC, KonradTajstra approved these changes

2023-09-11 10:42 UTC, merged